project:
  type: website
  output-dir: _site

website:
  title: "Tynan Challenor"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: assets/cv/Tynan_Challenor_CV.pdf
        text: CV
    right:
      - icon: github
        href: https://github.com/tynan-challenor
        aria-label: GitHub
      - icon: envelope
        href: mailto:tynanc@uw.edu
        aria-label: Email

format:
  html:
    theme:
      light: litera
      dark: darkly
    css: styles.css
    toc: true



